### ISSUE TITLE
Proposed changes for Morning session

### ISSUE THREAD

**Issue by itsmraga-hub** [uisendy/MyPortFolio#4]
# ⚠️ Issue 1

- I strongly suggest you use absolute paths in your href's i.e. ./file_name as it's even easier to link to files that are outside your file folder structure.
- I can see a nested nav menu inside another nav menu. It would be better if a nav menu was by itself since a portfolio website can only have a single nav bar.
- In your CSS file, I found a commented-out piece of code. I think it's better to practice to get rid of commented-out code when pushing code to your main Github repo. This helps in improving code security and it makes your code more readable.
- I can also see that the stylesheet linters are failing. For security purposes and good design, it would be better if all the [html/css Linters](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/clean-code/linters.md) passed.

**Comment by uisendy** [comment]
All task was completed. Thanks for the Correction and contributions
